name = "optimizely-product-description-tool"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env.production]
name = "optimizely-product-description-tool"

[env.staging]
name = "optimizely-product-description-tool-staging"
