name = "optimizely-product-description-tool"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[env.production]
name = "optimizely-product-description-tool"

[env.staging]
name = "optimizely-product-description-tool-staging"
